ALTER TABLE customer_invoice_items
  ADD COLUMN IF NOT EXISTS project_rate DECIMAL(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vehicle_mob DECIMAL(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vehicle_dimob DECIMAL(10,2) NOT NULL DEFAULT 0;
